### ISSUE TITLE
Couldn't get the pointer of the inject function.

### ISSUE THREAD

**Issue by oakieville** [ItzzExcel/LInjector#1]
always give error Couldn't get the pointer of the inject function.

**Comment by ItzzExcel** [comment]
This is because you didn't put the /libs folder in the same directory as the LInjector.cpp file, to fix this just do this, but it doesn't work, the project is unfinished, and I don't have enough time to complete it daily.
In the repository, there's a folder called libs, that folder, when you clone, it's in the main folder, but you need to put it in _/x64/Debug_ the folder that contains the _LInjector.exe_ file when you compile it.

**Comment by ItzzExcel** [comment]
I'm trying to fix it. I re-written all the code. It should work now.
Re download and re-compile pls.
